
%{

this is the code in /home/sergio/git/JGR_July2025/CODE
---------------------------------------------------------

     -rw-rw-r-- 1 sergio pi_sergio  5223 Jan 22  2026 set_zeroT_nofit.m
     -rw-rw-r-- 1 sergio pi_sergio  5566 Jan 22  2026 set_zeroWV_nofit.m
     -rw-rw-r-- 1 sergio pi_sergio  2577 Jan 22  2026 show_unc.m
     -rw-rw-r-- 1 sergio pi_sergio 16997 Jan 22  2026 strow_override_defaults_latbins_AIRS_fewlays.m
     -rw-rw-r-- 1 sergio pi_sergio  1159 Jan 22  2026 trop_index.m
     -rw-rw-r-- 1 sergio pi_sergio 19346 Jan 22  2026 set_driver_rateset_datafile.m
     -rw-rw-r-- 1 sergio pi_sergio 14498 Jan 22  2026 set_the_AMSU_jcobians.m
     -rw-rw-r-- 1 sergio pi_sergio 14651 Jan 22  2026 set_the_jacobians.m
     -rw-rw-r-- 1 sergio pi_sergio  5566 Jan 22  2026 set_zeroO3_nofit.m
     -rw-rw-r-- 1 sergio pi_sergio 16079 Jan 22  2026 set_apriori_ERA5_MERRA2_or_AIRSL3_MLS_geophysical.m
     -rw-rw-r-- 1 sergio pi_sergio  8911 Jan 22  2026 set_driver_jacfile.m
     -rw-rw-r-- 1 sergio pi_sergio  2348 Jan 22  2026 set_Tz_O3z_noFit.m
     -rw-rw-r-- 1 sergio pi_sergio   862 Jan 22  2026 nc_rates.m
     -rw-rw-r-- 1 sergio pi_sergio  2163 Jan 22  2026 precipitation_vs_skt_changes.m
     -rw-rw-r-- 1 sergio pi_sergio 11584 Jan 22  2026 see_clust_put_together_jacs_cldERA5_2022.m
     -rw-rw-r-- 1 sergio pi_sergio 18539 Jan 22  2026 set_CO2_CH4_N2O_ESRL.m
     -rw-rw-r-- 1 sergio pi_sergio  5687 Jan 22  2026 get_co2_n2o_ch4_for_strow_override.m
     -rw-rw-r-- 1 sergio pi_sergio  1960 Jan 22  2026 get_ESRL_TRACE_GAS_2002_2022.m
     -rw-rw-r-- 1 sergio pi_sergio  6701 Jan 22  2026 get_jac_fast.m
     -rw-rw-r-- 1 sergio pi_sergio  8750 Jan 22  2026 get_rates.m
     -rw-rw-r-- 1 sergio pi_sergio  5313 Jan 22  2026 jeevanjee_PBL_deltaRH_Ts.m
     -rw-rw-r-- 1 sergio pi_sergio   744 Jan 22  2026 combinejaclays.m
OOPS -rw-rw-r-- 1 sergio pi_sergio 27470 Jan 22  2026 do_the_cov_set_numbers.m  
     -rw-rw-r-- 1 sergio pi_sergio  1239 Jan 22  2026 estimate_fracWV_for_deltaRH_zero.m
     -rw-rw-r-- 1 sergio pi_sergio  6595 Jan 22  2026 find_the_oem_channels.m
     -rw-rw-r-- 1 sergio pi_sergio  2317 Jan 22  2026 find_wgtA_wgtB.m
     -rw-rw-r-- 1 sergio pi_sergio 54539 Jan 22  2026 clust_run_retrieval_setlatbin_AIRS_loop_lonbin.m
OOPS -rw-rw-r-- 1 sergio pi_sergio 36093 Jan 22  2026 build_cov_matrices.m
     -rw-rw-r-- 1 sergio pi_sergio  7251 Jan 22  2026 change_important_topts_settings.m
     -rw-rw-r-- 1 sergio pi_sergio  1495 Jan 22  2026 check_driver.m
     -rw-rw-r-- 1 sergio pi_sergio  7150 Jan 22  2026 check_settings.m
     -rw-rw-r-- 1 sergio pi_sergio  7259 Jan 22  2026 choose_goodchans_from_2645.m
     %}

%% ls -1 /home/sergio/git/JGR_July2025/CODE
list_files = {...
'build_cov_matrices.m',...
'change_important_topts_settings.m',...
'check_driver.m',...
'check_settings.m',...
'choose_goodchans_from_2645.m',...
'clust_run_retrieval_setlatbin_AIRS_loop_lonbin.m',...
'combinejaclays.m',...
'do_the_cov_set_numbers.m',...
'estimate_fracWV_for_deltaRH_zero.m',...
'find_the_oem_channels.m',...
'find_wgtA_wgtB.m',...
'get_co2_n2o_ch4_for_strow_override.m',...
'get_ESRL_TRACE_GAS_2002_2022.m',...
'get_jac_fast.m',...
'get_rates.m',...
'jeevanjee_PBL_deltaRH_Ts.m',...
'nc_rates.m',...
'precipitation_vs_skt_changes.m',...
'see_clust_put_together_jacs_cldERA5_2022.m',...
'set_apriori_ERA5_MERRA2_or_AIRSL3_MLS_geophysical.m',...
'set_CO2_CH4_N2O_ESRL.m',...
'set_driver_jacfile.m',...
'set_driver_rateset_datafile.m',...
'set_the_AMSU_jcobians.m',...
'set_the_jacobians.m',...
'set_Tz_O3z_noFit.m',...
'set_zeroO3_nofit.m',...
'set_zeroT_nofit.m',...
'set_zeroWV_nofit.m',...
'show_unc.m',...
'strow_override_defaults_latbins_AIRS_fewlays.m',...
'trop_index.m'};

iDo = -1;
if iDo > 0
  disp('diffing against /home/sergio/git/JGR_July2025/CODE/')
  for ii = 1 : length(list_files)
    clc
    differ = ['!diff ' list_files{ii} ' /home/sergio/git/JGR_July2025/CODE/.'];
    eval(differ)
    disp(' ')
    fprintf(1,'>>>> %3i of %3i : just diffed   < %30s >   ret to continue if big changes, see OOPS above\n',ii,length(list_files),list_files{ii});
    disp('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')    
    pause
  end
end  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% this is doing a diff against
% /home/sergio/nogit/JUNK/oem_climate_code/AIRS_gridded_STM_May2021_trendsonlyCLR
%   commit of July 25, 2024
%   commit 906703152c402d9a6bfb2285b710fd2e56cd2459 (HEAD)
%   Author: Sergio Machado <sergio@umbc.edu>
%   Date:   Thu Jul 25 17:50:16 2024 -0400
%     SSM : used this code for trend paper revision sent to Ryan and Larrabee V2
%

% see ReadmeQuick
%%%
%dir2 = '/umbc/rs/pi_sergio/WorkDirDec2025/oem_climate_code/Earlier_Tries_Jul2025JGR/July25_2024_commit_good/';
%dir1 = '/home/sergio/git/oem_climate_code/AIRS_gridded_STM_May2021_trendsonlyCLR/';
%%%
%diff_m_or_f_files(dir1,dir2);
%
% this is the list from    name_differences.txt

list_files = {...
'build_cov_matrices.m',...
'change_important_topts_settings.m',...
'check_settings.m',...
'clust_put_together_jacs.m',...
'clust_put_together_jacs_clr.m',...
'clust_put_together_jacs_clrERA5.m',...
'clust_run_retrieval_setlatbin_AIRS_loop_lonbin.m',...
'compute_feedbacks_generic_ecRad.m',...
'compute_feedbacks_regress_olr_sarta_calcs.m',...
'do_compute_save_UMBC_feedbacks.m',...
'do_feedbacks_wrt_globalSST.m',...
'do_the_cov_set_numbers.m',...
'driver_compare_05_10_15_20_spectral_rates.m',...
'driver_compare_cldy_Qtrends_2002_2022.m',...
'driver_contrast_obsrates_05_10_15_20.m',...
'driver_gather_gridded_anomaly_retrieval_results.m',...
'driver_gather_gridded_retrieval_results.m',...
'driver_put_together_QuantileChoose_anomalies.m',...
'driver_put_together_QuantileChoose_trends.m',...
'driver_read_kcarta_fluxes_for_paper.m',...
'driver_read_kcarta_radiances_for_paper.m',...
'figs_put_together_QuantileChoose_trends.m',...
'find_T_RH_trends.m',...
'gather_gridded_retrieval_results_plots.m',...
'get_ESRL_TRACE_GAS_2002_2022.m',...
'get_anomaly_processors.m',...
'get_co2_n2o_ch4_for_strow_override.m',...
'get_jac_fast.m',...
'get_rates.m',...
'get_the_mean_profiles.m',...
'guess_delta_ILR.m',...
'make_globalavg_and_onetile_anomaly.m',...
'plot_ERA_vs_UMBC.m',...
'plot_anomalies_All.m',...
'plot_driver_gather_gridded_retrieval_results.m',...
'read_fileMean17years.m',...
'savebigFATfile.m',...
'savesmallFATfile.m',...
'see_clust_put_together_jacs_clr.m',...
'see_clust_put_together_jacs_clrERA5_2012.m',...
'see_clust_put_together_jacs_clrERA5_2014.m',...
'see_clust_put_together_jacs_clrERA5_2021.m',...
'set_CO2_CH4_N2O_ESRL.m',...
'set_apriori_ERA5_MERRA2_or_AIRSL3_MLS_geophysical.m',...
'set_driver_jacfile.m',...
'set_driver_rateset_datafile.m',...
'set_the_jacobians.m',...
'simple_get_the_model_trends_do_feedbacks.m',...
'statistical_significance_sergio.m',...
'statistical_significance_strow.m',...
'strow_override_defaults_latbins_AIRS_fewlays.m',...
'wrapper_driver_gather_ALL_rates_AIRSL3_NWP_XMIP.m'};

iDo = -1;
if iDo > 0
  disp('diffing against ../Earlier_Tries_Jul2025JGR/July25_2024_commit_good/')
  disp('ret to continue'); pause
  for ii = 1 : length(list_files)
    clc
    differ = ['!diff ' list_files{ii} ' ../Earlier_Tries_Jul2025JGR/July25_2024_commit_good/.'];
    eval(differ)
    disp(' ')
    fprintf(1,'>>>> %3i of %3i : just diffed   < %30s >   ret to continue if big changes, see OOPS above\n',ii,length(list_files),list_files{ii});    
    disp('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
    pause
  end
end  

list_files = {
'build_cov_matrices.m',...
'clust_run_retrieval_setlatbin_AIRS_loop_lonbin.m',...
'do_the_cov_set_numbers.m',...
'set_CO2_CH4_N2O_ESRL.m',...
'set_apriori_ERA5_MERRA2_or_AIRSL3_MLS_geophysical.m',...
'strow_override_defaults_latbins_AIRS_fewlays.m'};

iDo = +1;
if iDo > 0
  disp('diffing against short essential list of ../Earlier_Tries_Jul2025JGR/July25_2024_commit_good/')
  disp('ret to continue'); pause  
  for ii = 1 : length(list_files)
    clc
    differ = ['!diff ' list_files{ii} ' ../Earlier_Tries_Jul2025JGR/July25_2024_commit_good/.'];
    eval(differ)
    disp(' ')
    fprintf(1,'>>>> %3i of %3i : just diffed   < %30s >   ret to continue if big changes, see OOPS above\n',ii,length(list_files),list_files{ii});    
    disp('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
    pause
  end
end  


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
iDo = input('load in BIG MAT files to compare against figs 3,5 of JGR paper (-1 default/+1) : ');
if length(iDo) == 0
  iDo = -1;
end
if iDo < 0
  disp('graceful exit')
  return
else
  disp('Proceeding ... waiti while I load in large files ...')
end

load iType_9_iQAX_3_convert_sergio_clearskygrid_obsonly_Q03.mat
load SyntheticTimeSeries_ERA5_AIRSL3_CMIP6/STS/NIGHTorAVG/ERA5/20yrs//ERA5_spectraltrends_2002_09_2022_08.mat

addpath /home/sergio/git/JGR_2025_PAPER/JGR_July2025/PLOTTER
make_jgr_fig3

figure(5); clf; plot(h.vchan,squeeze(nanmean(b_desc,1)))
figure(5); clf; plot(h.vchan,squeeze(nanmean(squeeze(nanmean(b_desc,1)),1)))
figure(6); clf; plot(h.vchan,squeeze(nanmean(squeeze(nanmean(b_err_desc,1)),1)))

%%%%%%%%%%%%%%%%%%%%%%%%%

figure(1); clf
figure(2); clf
figure(3); clf
make_jgr_fig5
ax = axis; cx = caxis;
figure(1); title('paper dBTObs/dt');
figure(2); title('paper noise');
figure(3); title('paper dBTCal/dt');

yy = unique(Y);
figure(7); clf; pcolor(h.vchan,yy,squeeze(nanmean(b_asc,1)))
figure(7); clf; pcolor(h.vchan,yy,squeeze(nanmean(b_desc,1)))
shading flat; colorbar; colormap(usa2); caxis(cx); axis(ax);

figure(8); clf;
pcolor(h.vchan,yy,data_fig5b.l1c_trendD - squeeze(nanmean(b_desc,1)))
shading flat; colorbar; colormap(usa2); caxis(cx/50); axis(ax);

wah = reshape(era5_rates_desc,2645,72,64);
figure(9); clf; pcolor(h.vchan,yy,squeeze(nanmean(wah,2))')
shading flat; colorbar; colormap(usa2); caxis(cx); axis(ax);

figure(10); clf; pcolor(h.vchan,yy,data_fig5c.era5-0*squeeze(nanmean(wah,2))')
shading flat; colorbar; colormap(usa2); caxis(cx/50); axis(ax);

figure(7);  title('new dBTObs/dt');
figure(8);  title('paper-new dBTObs/dt');
figure(9);  title('new dBTCal/dt');
figure(10); title('paper-new dBTCal/dt');
